In [1]:
import csv
import nltk
from nltk import Tree

### Getting character


Given an row of the CSV file as a parameter:

e.g. *row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']*

This function returns a list with the characters.
Each character has the name (or names) of the characters, the gender of the actor and the id of the actor (person id in the DB).

e.g. *[['Peter Parker', 'Spider-Man', 'Male', '1136406'], ["Michelle 'MJ' Jones", 'Female', '505710'], ['Stephen Strange', 'Doctor Strange', 'Male', '71580'], ['Ned Leeds', 'Male', '1649152']]*






In [2]:
def getCharacters(row):
    
    characters = []    
    
    characterNames1 = list(map(str.strip, row[2].split('/')))
    character1 = []
    for name in characterNames1:
        character1.append(name)
    character1.append(row[4])
    character1.append(row[5])
    characters.append(character1)
    
    characterNames2 = list(map(str.strip, row[6].split('/')))    
    character2 = []
    for name in characterNames2:
        character2.append(name)
    character2.append(row[8])
    character2.append(row[9])
    characters.append(character2)
        
    characterNames3 = list(map(str.strip, row[10].split('/')))    
    character3 = []
    for name in characterNames3:
        character3.append(name)
    character3.append(row[12])
    character3.append(row[13])
    characters.append(character3)
    
        
    characterNames4 = list(map(str.strip, row[14].split('/')))
    character4 = []
    for name in characterNames4:
        character4.append(name)
    character4.append(row[16])
    character4.append(row[17])
    characters.append(character4)
    
    return characters
    

In [3]:
# Test
row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']
print(getCharacters (row))

[['Peter Parker', 'Spider-Man', 'Male', '1136406'], ["Michelle 'MJ' Jones", 'Female', '505710'], ['Stephen Strange', 'Doctor Strange', 'Male', '71580'], ['Ned Leeds', 'Male', '1649152']]


-----

### Getting character names

Given an row of the CSV file as a parameter:

e.g. *row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']*

This function returns a list with names of the character. Not split by character. 

e.g. *['Peter Parker', 'Spider-Man', "Michelle 'MJ' Jones", 'Stephen Strange', 'Doctor Strange', 'Ned Leeds']*


In [4]:
def getCharacterNames(row):
    
    characterNames = []    
    
    characterNames1 = list(map(str.strip, row[2].split('/')))
    for name in characterNames1:
        characterNames.append(name)
    
    characterNames2 = list(map(str.strip, row[6].split('/')))    
    for name in characterNames2:
        characterNames.append(name)
        
    characterNames3 = list(map(str.strip, row[10].split('/')))    
    for name in characterNames3:
        characterNames.append(name)
        
    characterNames4 = list(map(str.strip, row[14].split('/')))
    for name in characterNames4:
        characterNames.append(name)
    
    return characterNames
    

In [5]:
# Test
row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']
print(getCharacterNames (row))

['Peter Parker', 'Spider-Man', "Michelle 'MJ' Jones", 'Stephen Strange', 'Doctor Strange', 'Ned Leeds']


----

### Getting characters

Given an row of the CSV file as a parameter:

e.g. *row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']*

This function returns a list with the characters. 
Each character is represented by one list, where the first item is the name (or names) of the characters, and then, 
the gender of the actor and the id of the actor (person id in the DB).

e.g. *[[['Peter Parker', 'Spider-Man'], 'Male', '1136406'], [["Michelle 'MJ' Jones"], 'Female', '505710'], [['Stephen Strange', 'Doctor Strange'], 'Male', '71580'], [['Ned Leeds'], 'Male', '1649152']]*



In [6]:
def getCharacter(row):
    
    characters = []    
    
    characterNames1 = list(map(str.strip, row[2].split('/')))
    character1 = []
    character1.append(characterNames1)
    character1.append(row[4])
    character1.append(row[5])
    characters.append(character1)    
    
    characterNames2 = list(map(str.strip, row[6].split('/')))   
    character2 = []
    character2.append(characterNames2)
    character2.append(row[8])
    character2.append(row[9])
    characters.append(character2)
            
    characterNames3 = list(map(str.strip, row[10].split('/')))    
    character3= []
    character3.append(characterNames3)
    character3.append(row[12])
    character3.append(row[13])
    characters.append(character3)
            
    characterNames4 = list(map(str.strip, row[14].split('/')))
    character4= []
    character4.append(characterNames4)
    character4.append(row[16])
    character4.append(row[17])
    characters.append(character4)
    
    return characters

In [7]:
# Test
row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']
print(getCharacter (row))

[[['Peter Parker', 'Spider-Man'], 'Male', '1136406'], [["Michelle 'MJ' Jones"], 'Female', '505710'], [['Stephen Strange', 'Doctor Strange'], 'Male', '71580'], [['Ned Leeds'], 'Male', '1649152']]


In [8]:
def getNamesByCharacter(row):
    
    characterNames = []    
    
    characterNames1 = list(map(str.strip, row[2].split('/')))
    characterNames.append(characterNames1)
    
    characterNames2 = list(map(str.strip, row[6].split('/')))    
    characterNames.append(characterNames2)
        
    characterNames3 = list(map(str.strip, row[10].split('/')))    
    characterNames.append(characterNames3)
        
    characterNames4 = list(map(str.strip, row[14].split('/')))
    characterNames.append(characterNames4)
    
    return characterNames

In [9]:
# Test
row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']
print(getNamesByCharacter (row))

[['Peter Parker', 'Spider-Man'], ["Michelle 'MJ' Jones"], ['Stephen Strange', 'Doctor Strange'], ['Ned Leeds']]


-----

### Get Sentences where a character is named

Given an row of the CSV file as a parameter:

e.g. *row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']*

This function returns only the sentences where a character is named + the name of the character + the gender or the caracter + the person id. 

eg. *[[['Peter Parker', 'Spider-Man'], 'Male', '1136406'], 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero.']
[[['Peter Parker', 'Spider-Man'], 'Male', '1136406'], 'When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']
[[['Stephen Strange', 'Doctor Strange'], 'Male', '71580'], 'When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']*


In [10]:
def getSentencesAboutAnyCharacter(row):
    
    characters = getCharacter(row)    
    overview = row[18]    
    
    sentencesThatMentionCharacters = []
    
    for sentence in nltk.sent_tokenize(overview):        
        for character in characters:            
            for name in character[0]:                
                if name in sentence:
                    sentencesThatMentionCharacters.append([character, sentence])
                    break
        
    return sentencesThatMentionCharacters
        

In [11]:
# test
row = ['634649', 'Spider-Man: No Way Home', 'Peter Parker / Spider-Man', 'Tom Holland', 'Male', '1136406', "Michelle 'MJ' Jones", 'Zendaya', 'Female', '505710', 'Stephen Strange / Doctor Strange', 'Benedict Cumberbatch', 'Male', '71580', 'Ned Leeds', 'Jacob Batalon', 'Male', '1649152', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']

for sentence in getSentencesAboutAnyCharacter(row):
    print(sentence)


[[['Peter Parker', 'Spider-Man'], 'Male', '1136406'], 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero.']
[[['Peter Parker', 'Spider-Man'], 'Male', '1136406'], 'When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']
[[['Stephen Strange', 'Doctor Strange'], 'Male', '71580'], 'When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.']


In [12]:
# test
row = ['399566', 'Godzilla vs. Kong', 'Dr. Nathan Lind', 'Alexander Skarsgård', 'Male', '28846', 'Madison Russell', 'Millie Bobby Brown', 'Female', '1356210', 'Dr. Ilene Andrews', 'Rebecca Hall', 'Female', '15556', 'Bernie Hayes', 'Brian Tyree Henry', 'Male', '226366', 'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.']
print(getSentencesAboutAnyCharacter(row))

[]


---

### Get chunks from sentences where a character is named

Given a list of tags (result of the method nltk.pos_tag) 

like: 
`tags = [nltk.pos_tag(token) for token in tokens]`
 
 
e.g. *tags = [[('Peter', 'NNP'), ('Parker', 'NNP'), ('is', 'VBZ'), ('unmasked', 'JJ'), ('and', 'CC'), ('no', 'DT'), ('longer', 'RBR'), ('able', 'JJ'), ('to', 'TO'), ('separate', 'VB'), ('his', 'PRP$'), ('normal', 'JJ'), ('life', 'NN'), ('from', 'IN'), ('the', 'DT'), ('high-stakes', 'NNS'), ('of', 'IN'), ('being', 'VBG'), ('a', 'DT'), ('super-hero', 'NN'), ('.', '.')]]*

This function returns only the `NP chunks` that match with the gramatical pattern:
**{<DT|PP|PRP\$>?<JJ.*>+<CC>*<JJ.*>*<NN.*>+}"**

e.g. *[Tree('NP', [('his', 'PRP$'), ('normal', 'JJ'), ('life', 'NN')])]*

In [13]:
def getCharacterNounPhraseChunks(tags):
    
    grammar = "NP: {<DT|PP|PRP\$>?<JJ.*>+<CC>*<JJ.*>*<NN.*>+}"  # det(opcional), adj(cero, uno o más), nombre
    cp = nltk.RegexpParser(grammar) # chunk parser
    
    npChucks = []
    
    for tag in tags:
        result = cp.parse(tag)        
        for i in result.subtrees(filter=lambda x: x.label() == 'NP'):
            npChucks.append(i)
    
    return npChucks

In [14]:
#Test
tags = [[('Peter', 'NNP'), ('Parker', 'NNP'), ('is', 'VBZ'), ('unmasked', 'JJ'), ('and', 'CC'), ('no', 'DT'), ('longer', 'RBR'), ('able', 'JJ'), ('to', 'TO'), ('separate', 'VB'), ('his', 'PRP$'), ('normal', 'JJ'), ('life', 'NN'), ('from', 'IN'), ('the', 'DT'), ('high-stakes', 'NNS'), ('of', 'IN'), ('being', 'VBG'), ('a', 'DT'), ('super-hero', 'NN'), ('.', '.')]]
getCharacterNounPhraseChunks(tags)

[Tree('NP', [('his', 'PRP$'), ('normal', 'JJ'), ('life', 'NN')])]

-----

Given an overview of a movie as parameter: 

e.g. *overview= "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady."*

This function returns only the NP chunks that match with the gramatical pattern: 

**{<DT|PP|PRP$>?<JJ.>+<JJ.><NN.*>+}**

e.g. *[Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')]),* 

*Tree('NP', [('the', 'DT'), ('alien', 'JJ'), ('symbiote', 'NN')]), Tree('NP', [('a', 'DT'), ('new', 'JJ'), ('enemy', 'NN')]),* 

*Tree('NP', [('serial', 'JJ'), ('killer', 'NN'), ('Cletus', 'NNP'), ('Kasady', 'NNP')])]* 



In [15]:
def getTokensTagsAndCharNPChunks(overview):
    sentences = nltk.sent_tokenize(overview) # split in sentences
    tokens = [nltk.word_tokenize(sent) for sent in sentences] #split in words (tokens)
    tags = [nltk.pos_tag(token) for token in tokens] #add tag (noun, verb, adj...)
    expressions = getCharacterNounPhraseChunks(tags)
    return expressions

In [16]:
#Test
overview= "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady."
tokens = getTokensTagsAndCharNPChunks(overview)
print(tokens)


[Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')]), Tree('NP', [('the', 'DT'), ('alien', 'JJ'), ('symbiote', 'NN')]), Tree('NP', [('a', 'DT'), ('new', 'JJ'), ('enemy', 'NN')]), Tree('NP', [('serial', 'JJ'), ('killer', 'NN'), ('Cletus', 'NNP'), ('Kasady', 'NNP')])]


-----

Give one or more character's name(s) and a chunk as a parameter, this function returns true if the character appears in the chunk. 

In [17]:
def hasChunkTheCharacter(character,chunk):    
    for word in chunk:
        for name in character:
            for part in name.split():
                if part == word[0]:
                    return True
    return False

In [18]:
# test
character = ['Eddie Brock', 'Venom']
chunk = Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])

hasChunkTheCharacter(character,chunk)

True

----

Given a list of chunks as a parameter (allChunks) and the name (or the names) of one character, it returns the chunks that name that character

In [19]:
def getChunksWithCharacter(character, allChunks):
    
    
    characterChunks = []
    
    for chunk in allChunks:
        if hasChunkTheCharacter(character,chunk):
            characterChunks.append(chunk)
    
    return characterChunks       
        
            

In [20]:
#Test 

character = ['Eddie Brock', 'Venom']
allChunks = [Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')]), 
             Tree('NP', [('the', 'DT'), ('alien', 'JJ'), ('symbiote', 'NN')]), 
             Tree('NP', [('a', 'DT'), ('new', 'JJ'), ('enemy', 'NN')]), 
             Tree('NP', [('serial', 'JJ'), ('killer', 'NN'), ('Cletus', 'NNP'), ('Kasady', 'NNP')])]


getChunksWithCharacter(character, allChunks)

[Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])]

In [21]:
#Test

character = "Cletus Kasady"
allChunks = [Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')]), 
             Tree('NP', [('the', 'DT'), ('alien', 'JJ'), ('symbiote', 'NN')]), 
             Tree('NP', [('a', 'DT'), ('new', 'JJ'), ('enemy', 'NN')]), 
             Tree('NP', [('serial', 'JJ'), ('killer', 'NN'), ('Cletus', 'NNP'), ('Kasady', 'NNP')])]


getChunksWithCharacter(character, allChunks)

[Tree('NP', [('a', 'DT'), ('new', 'JJ'), ('enemy', 'NN')])]

---

### Get NP chunks where a character is named, from an line of the csv file

Given a row of the csv file:

e.g.

*line =\
        ['580489', 
        'Venom: Let There Be Carnage', \
        'Eddie Brock / Venom', 'Tom Hardy', 'Male', '2524', \
        'Cletus Kasady / Carnage', 'Woody Harrelson', 'Male', '57755', \
        'Anne Weying', 'Michelle Williams', 'Female', '1812', \
        'Frances Louise Barrison / Shriek', 'Naomie Harris', 'Female', '2038', \
        'After finding a host body in investigative reporter Eddie Brock, \
         the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.']*
         
         
this function returns the NP Chunks where the characters are named + the name(s) of the character + gender + person id 

e.g.

*[[['Eddie Brock', 'Venom'], 'Male', '2524'], [Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])]]
[[['Cletus Kasady', 'Carnage'], 'Male', '57755'], [Tree('NP', [('serial', 'JJ'), ('killer', 'NN'), ('Cletus', 'NNP'), ('Kasady', 'NNP')])]]*


In [22]:
def getNPs(line):
    
    allCharacterChunks = []
    
    sentences = getSentencesAboutAnyCharacter(line)
    
    for sentence in sentences:
        character = sentence[0]
        overview = sentence[1]        
        allChunks = getTokensTagsAndCharNPChunks(overview)
        characterChunks= getChunksWithCharacter(character[0], allChunks)
        if len(characterChunks) > 0:
            allCharacterChunks.append([character, characterChunks])
        
    return allCharacterChunks
        

In [23]:
# test
line = ['580489', 
        'Venom: Let There Be Carnage', 
        'Eddie Brock / Venom', 'Tom Hardy', 'Male', '2524', 
        'Cletus Kasady / Carnage', 'Woody Harrelson', 'Male', '57755', 
        'Anne Weying', 'Michelle Williams', 'Female', '1812', 
        'Frances Louise Barrison / Shriek', 'Naomie Harris', 'Female', '2038', 
        'After finding a host body in investigative reporter Eddie Brock, \
         the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.']

nps = getNPs(line)
for np in nps:
    print(np)



[[['Eddie Brock', 'Venom'], 'Male', '2524'], [Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])]]
[[['Cletus Kasady', 'Carnage'], 'Male', '57755'], [Tree('NP', [('serial', 'JJ'), ('killer', 'NN'), ('Cletus', 'NNP'), ('Kasady', 'NNP')])]]


----

### Get Adjetives from a NP Chunk:

Gives one NP chunk as a parameter "nounPhraseChunk", and a list of character name(s):

e.g.
*nounPhraseChunk = Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])*
*characterNames = ['Eddie Brock', 'Venom']* 

Get the adjetives o names (that represents a role) of that NP Chunk (but not the name, determinant, conjuntion, u other tokens of the sentence)

e.g.
*['investigative', 'reporter']* 


In [24]:
def getAdjetivesAndRemoveCharacterName(nounPhraseChunk:Tree, characterNames:list):    
    
    # create all the combinations: only name, only surname, complete name, etc.. in characterNames
    allCombinations = []
    for name in characterNames:
        allCombinations.append(name)
    
    for name in characterNames:
        for part in name.split():
            if part not in characterNames:
                allCombinations.append(part)
    
    #remove name and adjetives    
    adjetives = []
    for part in nounPhraseChunk:
        if part[0] not in allCombinations and part[0]!='–' and part[1] != 'PRP$' and part[1] != 'DT' and part[1] != 'CC' and part[1] != 'JJS':
            adjetives.append(part[0].lower())        

    return adjetives


In [25]:
# Test
np = Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])
characterNames = ['Eddie Brock', 'Venom']
getAdjetivesAndRemoveCharacterName(np, characterNames)

['investigative', 'reporter']

---

Given a list with the character names, reduce it to the three first names (if there are less than three fill with empty strings) for the csv.
If we have more than three an error is printed

In [26]:
def getThreeNames(characterNames:list):
    
    names = characterNames
    lenNamesList = len(names)
    if lenNamesList <= 3:
        for i in range(0, 3-lenNamesList):
            names.append("")
    else:
        print("Error! I found more than three names for a character!!! ", characterNames)
    
    return names
    

In [27]:
# Test
characterNames = ['Eddie Brock', 'Venom']
getThreeNames(characterNames)

['Eddie Brock', 'Venom', '']

---

### Builds a row for the output CSV file

returns one or several rows with this fields: 

year, movieid, charactername1; charactername2; charactername3; sex; actorid; adj;

one row for each adjetive: 

In [28]:
def getCSVSingleAdejetiveRow(year, movieid, np):
    
    rows = []
    
    character = np[0]
    threeCharacterNames = getThreeNames(character[0])
    characterSex = character[1]     
    characterIdPerson = character[2]
    adjetives = getAdjetivesAndRemoveCharacterName(np[1][0], threeCharacterNames)
    
     # year, movieid, charactername1; charactername2; charactername3; sex; actorid; adj;
    for adj in adjetives:
        row = []  
        row.append(year)
        row.append(movieid)

        for tname in threeCharacterNames:
            row.append(tname)

        row.append(characterSex)
        row.append(characterIdPerson)    
        row.append(adj)
        
        rows.append(row)
        
    
    
    return rows
    
    


In [29]:
year=2021
movieid=580489
np = [[['Eddie Brock', 'Venom'], 'Male', '2524'], [Tree('NP', [('investigative', 'JJ'), ('reporter', 'NN'), ('Eddie', 'NNP'), ('Brock', 'NNP')])]]

getCSVSingleAdejetiveRow(year, movieid, np)

[[2021, 580489, 'Eddie Brock', 'Venom', '', 'Male', '2524', 'investigative'],
 [2021, 580489, 'Eddie Brock', 'Venom', '', 'Male', '2524', 'reporter']]

------------

------------

### Main


   Open CSV:

In [30]:
total_rows_female = []
total_rows_male = []
total_rows_unknown = []

for year in range(2021, 2022):
    file_title = 'csv2/movies_'+str(year)+'.csv'
    with open(file_title, mode='r',  encoding='utf-8') as file:
        csvFile = csv.reader(file, delimiter = ';')

        csv_headings = next(csvFile)   # print (csv_headings)

        for (line,i) in zip(csvFile, range(0,300)):  
            nps = getNPs(line)
            if len(nps)> 0:
                for np in nps:
                    rows = getCSVSingleAdejetiveRow(year, line[0], np)
                    for row in rows:
                        if row[5] == 'Female':
                            total_rows_female.append(row)
                        elif row[5] == 'Male':
                            total_rows_male.append(row)                        
                        else:
                            total_rows_unknown.append(row)
                        
                        

        

Write to csv - females

In [31]:
header = ['year', 'movieid', 'charactername1', 'charactername2', 'charactername3', 'sex', 'actorid', 'adj']


# open the file in the write mode
csvfile = open('csv2/file_individual_adj_female.csv', 'w', encoding='UTF8', newline='')

# create the csv writer
csv_writer = csv.writer(csvfile, delimiter = ';')

# write the header to the csv file
csv_writer.writerow(header)

for row in total_rows_female:  
    csv_writer.writerow(row)

# close the file
csvfile.close()

Write to csv - male

In [32]:

header = ['year', 'movieid', 'charactername1', 'charactername2', 'charactername3', 'sex', 'actorid', 'adj']


# open the file in the write mode
csvfile = open('csv2/file_individual_adj_male.csv', 'w', encoding='UTF8', newline='')

# create the csv writer
csv_writer = csv.writer(csvfile, delimiter = ';')

# write the header to the csv file
csv_writer.writerow(header)

for row in total_rows_male:  
    csv_writer.writerow(row)

# close the file
csvfile.close()
        


Write to csv - others (unknown)

In [33]:
header = ['year', 'movieid', 'charactername1', 'charactername2', 'charactername3', 'sex', 'actorid', 'adj']


# open the file in the write mode
csvfile = open('csv2/file_individual_adj_others.csv', 'w', encoding='UTF8', newline='')

# create the csv writer
csv_writer = csv.writer(csvfile, delimiter = ';')

# write the header to the csv file
csv_writer.writerow(header)

for row in total_rows_unknown:  
    csv_writer.writerow(row)

# close the file
csvfile.close()